# Generated by Django 5.1.7 on 2025-03-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huaqi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="account_name",
            field=models.CharField(default="尊贵的用户", max_length=100),
        ),
    ]
