# Generated by Django 5.1.7 on 2025-03-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huaqi", "0002_userinfo_account_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="earth_rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateField()),
                ("country", models.CharField(max_length=100)),
                ("currency", models.CharField(max_length=100)),
                ("currency_sign", models.CharField(max_length=100)),
                ("currency1_name", models.CharField(max_length=100)),
                (
                    "currency_rate1",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("currency2_name", models.CharField(max_length=100)),
                (
                    "currency_rate2",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("currency3_name", models.CharField(max_length=100)),
                (
                    "currency_rate3",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("currency4_name", models.CharField(max_length=100)),
                (
                    "currency_rate4",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("currency5_name", models.CharField(max_length=100)),
                (
                    "currency_rate5",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("currency6_name", models.CharField(max_length=100)),
                (
                    "currency_rate6",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("currency7_name", models.CharField(max_length=100)),
                (
                    "currency_rate7",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("currency8_name", models.CharField(max_length=100)),
                (
                    "currency_rate8",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                (
                    "currency9_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "currency_rate9",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
            ],
        ),
    ]
