# Generated by Django 5.1.7 on 2025-03-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huaqi", "0006_news_2024"),
    ]

    operations = [
        migrations.CreateModel(
            name="policy_2024",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                ("affect_currency", models.CharField(max_length=500)),
                ("affect_country", models.CharField(max_length=500)),
                ("text_vectors", models.TextField()),
            ],
        ),
    ]
