# Generated by Django 5.1.7 on 2025-03-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huaqi", "0007_policy_2024"),
    ]

    operations = [
        migrations.CreateModel(
            name="basic_info_2024",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                ("currency", models.CharField(max_length=500)),
                ("cpi", models.CharField(max_length=500)),
                ("gdp", models.CharField(max_length=500)),
                ("pmi", models.CharField(max_length=500)),
                ("ppi", models.CharField(max_length=500)),
                ("cci", models.CharField(max_length=500)),
                ("unemployment", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="date_currency_rates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateField()),
                ("currency_1", models.CharField(max_length=100)),
                ("currency_2", models.CharField(max_length=100)),
                ("predict_rate", models.DecimalField(decimal_places=6, max_digits=10)),
                ("true_rate", models.DecimalField(decimal_places=6, max_digits=10)),
                ("deal_year", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="date_currency_rate",
        ),
    ]
